apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: istio-installation
spec:
  # NOTE, if you remove all children from an element, you should remove the
  # element too.  An empty element is interpreted as null and will override all
  # default values (i.e. no values will be specified for that element, not even
  # the defaults baked into the chart values.yaml).
  istio:
    multitenant: false
    launcher:
      enabled: false
    # nodeagent:
    #   enabled: false
    #   image: docker.io/istio/node-agent-k8s:1.1.9
    #   env:
    #     CA_PROVIDER: "Citadel"
    #     CA_ADDR: "istio-citadel:8060"
    #     VALID_TOKEN: true
    global:
      # force to use rhel7 based proxy-init container
      proxy_init:
        image: proxy-init
      hub: registry.redhat.io/openshift-istio-tech-preview
      tag: 0.11.1
      # the following lines enable tls across the control and data planes
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: false
      disablePolicyChecks: true
      policyCheckFailOpen: false
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY # defaults to ALLOW_ANY
      # its either * or . - in case we can test all use cases, lets start with . in our dev env only
      # this will set the following in the config map: 
      # defaultServiceExportTo:
      #   - "."
      # defaultVirtualServiceExportTo:
      #   - "."
      # defaultDestinationRuleExportTo:
      #   - "."
      defaultConfigVisibilitySettings:
        - "*" # bookinfo didn't even work for me without it (even when I exported the GW and VS)
      proxy:
        accessLogFile: /dev/stdout # in envs higher than test this should be empty
        accessLogEncoding: TEXT
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      # sds:
      #   enabled: false
      #   udsPath: "unix:/var/run/sds/uds_path" #just a test to see if we pass the selinux hurdle
      #   useNormalJwt: true
    gateways:
      istio-egressgateway:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
        autoscaleEnabled: false
        # sds:
        #   enabled: true
        #   image: docker.io/istio/node-agent-k8s:1.1.9
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
        # sds:
        #   enabled: false
        #   image: docker.io/istio/node-agent-k8s:1.1.9
    mixer:
      policy:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G
    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0
      resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
    kiali:
      enabled: true
      tag: 0.20.0
    tracing:
      enabled: true
      hub: distributed-tracing-tech-preview
      tag: 1.11
